[env:stm32l412k8]
platform = ststm32
board = nucleo_l412kb
framework = arduino

board_upload.maximum_size = 65536
debug_tool = stlink
upload_protocol = stlink
build_flags =   -Os -flto 
extra_scripts = pre:inject_epoch.py
debug_speed = 4000

lib_deps =
    stm32duino/STM32duino Low Power
    stm32duino/STM32duino RTC
    C:\Users\moeburn\Documents\platformio\libs\U8g2_Arduino-master
