[env:stm32l412k8]
platform = ststm32
board = nucleo_l412kb
framework = arduino

board_upload.maximum_size = 65536

upload_protocol = serial

build_flags =   -Os -flto


lib_deps =
    stm32duino/STM32duino Low Power
    stm32duino/STM32duino RTC
    C:\Users\moeburn\Documents\platformio\libs\U8g2_Arduino-master
    adafruit/RTClib@^2.1.4
    wollewald/INA219_WE@^1.4.1
    adafruit/Adafruit AHTX0
    adafruit/Adafruit BMP280 Library

lib_ignore = TinyWireM
